[project]
name = "python-bind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "pybind11>=3.0.1",
    "setuptools>=80.9.0",
    "uvicorn>=0.35.0",
]
